# Connexion a la Base de Data.
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate: #ORM Object Relational Mapping
      ddl-auto: update #Data Definition Language
    output:
      ansi:
        enabled: always
    h2:
      console:
        enabled: true

